[tasks.watch]
args = ["watch", "-c", "-x", "make submit"]
command = "cargo"
install_crate = "cargo-watch"

[tasks.watch_test_coverage]
args = ["watch", "-c", "-x", "tarpaulin --skip-clean --locked"]
command = "cargo"
install_crate = "cargo-watch"

[tasks.run]
args = ["run"]
command = "cargo"

[tasks.format]
args = ["fmt", "--all"]
command = "cargo"

[tasks.check]
args = ["check", "--all-features"]
command = "cargo"

[tasks.lint]
args = [
    "clippy",
    "--all-features",
    "--",
    "-D",
    "warnings",
    "-D",
    "clippy::unwrap_used",
    "-D",
    "clippy::expect_used",
    "-D",
    "clippy::panic",
    "-D",
    "unused_must_use",
]
command = "cargo"

[tasks.test]
args = ["test", "--all-features"]
command = "cargo"

[tasks.test_coverage]
args = ["tarpaulin", "--skip-clean", "--locked"]
command = "cargo"
install_crate = "tarpaulin"


# workflows

[tasks.check_all]
dependencies = ["check", "format", "lint"]

[tasks.submit]
dependencies = ["check", "test", "lint"]

# aliases

[tasks.w]
alias = "watch"

[tasks.r]
alias = "run"

[tasks.c]
alias = "check_all"

[tasks.s]
alias = "submit"

[tasks.tc]
alias = "test_coverage"

[tasks.wtc]
alias = "watch_test_coverage"
